apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cbk321fh8-go 
  janus-idp.io/tekton: cbk321fh8-go
  backstage.io/kubernetes-id: cbk321fh8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cbk321fh8-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  